# Boat lengths
BARCO_1_LENGTH = 1
BARCO_2_LENGTH = 2
BARCO_3_LENGTH = 3
BARCO_4_LENGTH = 4

# Boat quantities
BARCO_1_QUANTITY = 4
BARCO_2_QUANTITY = 3
BARCO_3_QUANTITY = 2
BARCO_4_QUANTITY = 1

BOARD_SIZE=10